version: '3.8'

services:
    app:
        build:
            context: .
        container_name: tms_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - vendor:/var/www/html/vendor
        depends_on:
            - db
        networks:
            - tms_network

    db:
        image: mysql:8
        restart: always
        container_name: tms_db
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - db_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - tms_network

volumes:
    db_data:
    vendor:

networks:
    tms_network:
        driver: bridge
